[project]
name = "website-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flet[all]>=0.28.3",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "xlsxwriter>=3.2.5",
]
